version: "3.8"

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx
    ports:
      - '443:443'
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/html

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/ybenlafk/Desktop/tmp/wp
    
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/ybenlafk/Desktop/tmp/db

networks:
  inception:
    driver: bridge
